### ISSUE TITLE
ModuleNotFoundError in tokenizer.py

### ISSUE THREAD

**Issue by BelowzeroA** [ai-forever/OCR-model#2]
[/usr/local/lib/python3.7/dist-packages/ocr/tokenizer.py](https://localhost:8080/#) in <module>()
      1 import torch
      2 
----> 3 `from ctcdecode import CTCBeamDecoder`
      4 
      5 

ModuleNotFoundError: No module named 'ctcdecode'

**Comment by skalinin** [comment]
You need to install [ctcdecode](https://github.com/ai-forever/OCR-model/blob/master/Dockerfile#L29)
pip3 install git+https://github.com/parlance/ctcdecode

**Comment by BelowzeroA** [comment]
> You need to install [ctcdecode](https://github.com/ai-forever/OCR-model/blob/master/Dockerfile#L29) pip3 install git+https://github.com/parlance/ctcdecode

True, thank you. I mean, it's not a bad idea to add ctcdecode to requirements.txt

**Comment by skalinin** [comment]
yeah... but sadly parlance/ctcdecode installing will crash, if I add it to requirements.txt

It has its own dependencies which need to be installed before we start to install ctcdecode itself (like torch).

**Comment by skalinin** [comment]
Updated [setup.py](https://github.com/ai-forever/OCR-model/blob/master/setup.py) - now parlance/ctcdecode is installed with all other packages via `python setup.py install`
